### ISSUE TITLE
Contributor Profile

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/workstreams-app#34]
Idea from bordumb:

Asking here as my mental for work-streams is managing contributions/contributors 

Will there be a concept of a user profile/page?

I’m imagining something like a page for me — bordumb — that’d give some high level overview of contributions I’ve made 

If so, where could I find designs for that? If not, any plan for such a page?

![https://discord.com/assets/263a7f4eeb6f69e46d969fa479188592.svg](https://discord.com/assets/263a7f4eeb6f69e46d969fa479188592.svg)

**Comment by juliendonck** [comment]
@efstajas I think I have an idea on how to make this work. Might take a stab at this

**Comment by juliendonck** [comment]
This has been implemented, you can click on any user now.
