### ISSUE TITLE
Empty dashboard

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/workstreams-app#44]
Remove filters on empty dashboard. Also is the button supposed to be there?

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/4406983/165541622-57709d0e-165e-4d2d-a06b-e0cac8ef7eac.png">

**Comment by efstajas** [comment]
@brandonhaslegs Ya button is supposed to be there since you're logged in. Filters have been removed now.

I guess we would use the same empty state component here we use when you're logged out and attempting to access the dashboard, yeah? Obviously with different copy.

**Comment by brandonhaslegs** [comment]
Yep. And if possible having the button not just floating out in outerspace like that.

**Comment by brandonhaslegs** [comment]
@efstajas actually in #38 there's a design for it.
