### ISSUE TITLE
Merge walletStore and authStore

### ISSUE THREAD

**Issue by efstajas** [radicle-dev/workstreams-app#50]
Currently, wallet connection is handled in `walletStore`, and authentication with the API is handled in `authStore`, and we have a third, derived store value called `connectedAndLoggedIn` that is the de-facto source of truth for whether a user should be shown as "logged in" or "logged out". While this sounds nice, in practice there is already tight coupling between the two stores (`walletStore.disconnect` calls `authStore.clear`) and we need to constantly check both `$connectedAndLoggedIn` and `$walletStore.connected` if we want to access the user's address anywhere, due to typescript.

It'd be better to refactor the two separate stores into a single one that handles authentication and wallet in one set of logic, given that the two are so tightly connected.

**Comment by juliendonck** [comment]
@efstajas that's done, no?

**Comment by juliendonck** [comment]
@efstajas ping

**Comment by efstajas** [comment]
@juliendonck Apologies, missed this. They're still separate stores now, but no longer tightly coupled, which makes it less problematic. I think we can close this issue for now and maybe reopen if we run into any problem with the current approach in the future :)
