### ISSUE TITLE
Improve human-readable duration formatting

### ISSUE THREAD

**Issue by efstajas** [radicle-dev/workstreams-app#56]
Currently, we store the duration of grants in days, and display it in either days or weeks. If you set a duration of 365 days, you see a value of 52 weeks: 

<img width="474" alt="Screenshot 2022-05-02 at 10 59 16" src="https://user-images.githubusercontent.com/1018218/166210079-cecf85bf-ebf1-4b74-8078-bdd55e626ca0.png">

365 days will likely be a common occurence given that some orgs may treat "roles" as just year-long grants. We should at the very least display 365 days as "1 year", and perhaps generally adopt a more flexible system that can format durations as weeks, months or years depending on what is most appropriate, and possibly also displays the absolute amount of days on hover.

**Comment by juliendonck** [comment]
Already improved this somewhat. Covering most of the basics. Wondering how we would specifically improve it.

**Comment by juliendonck** [comment]
@efstajas What exactly should we improve here? I don't see this as an issue right now

**Comment by efstajas** [comment]
Yep I'd say your PR fixed it 👍
