### ISSUE TITLE
Use appropriate aprostraphes

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/workstreams-app#67]
The only one I see so far is just

- [ ] "Workstreams you've applied to"

but Just for your information you can read more about this here: https://smartquotesforsmartpeople.com

**Comment by efstajas** [comment]
![image](https://user-images.githubusercontent.com/1018218/166647272-a0e1d9d5-eb5e-4338-9268-52eff10ec42d.png)

Anyway, that particular headline has been replaced with "Workstreams you applied to" with the new dashboard PR anyway, so closing this for now. :)
