### ISSUE TITLE
Move all workstreams- and applications-related fetching logic to `workstreamsStore` 

### ISSUE THREAD

**Issue by efstajas** [radicle-dev/workstreams-app#81]
In #80, I added `fetchWorkstreams` and `fetchWorkstream` functions to `workstreamsStore`, and started using them on the Explore page and Workstream detail page. We shouuld standardize all workstreams- and applications-related fetching logic there and start using it across the board in order to make subsequent optimizations (e.g. caching with SessionStorage) easier to implement.

**Comment by juliendonck** [comment]
This is almost done no? @efstajas

**Comment by efstajas** [comment]
#97 linked ✔️
