### ISSUE TITLE
Occasionally the previous page gets rendered with 0 opacity above the current page

### ISSUE THREAD

**Issue by efstajas** [radicle-dev/workstreams-app#84]
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/1018218/167625066-009b0158-8ff0-4a9d-8e89-1fac77b71975.png">

Seems to be an issue with SvelteKit directly or somehow caused by our page transition. Need to investigate more. Unclear how to reliably reproduce — seems random ATM.

**Comment by juliendonck** [comment]
@efstajas When I remove all svelte animation things, this doesn't happen anymore.

**Comment by efstajas** [comment]
![image](https://user-images.githubusercontent.com/1018218/169014999-78677c4d-bf48-4edf-a012-61c3ababac7e.png)

Issue still appears, reopening.
