### ISSUE TITLE
Viewing an open application shows duplicated content

### ISSUE THREAD

**Issue by efstajas** [radicle-dev/workstreams-app#88]
<img width="736" alt="image" src="https://user-images.githubusercontent.com/1018218/167852400-954ff32e-8b89-4e6d-aea1-b8e0a5ac86f6.png">

**Comment by juliendonck** [comment]
This is fixed in #82

**Comment by juliendonck** [comment]
https://github.com/radicle-dev/workstreams-app/pull/82/files#diff-20f1f813314ece01d941ad5fb92887121574cce1b45d8e28367e64a7150390d5
